# .github/actions/run-lint/action.yml

name: 'Run Linter'
description: 'Runs ESLint to check code quality'

runs:
  using: "composite"
  steps:
    - name: Run linter
      shell: bash
      run: yarn lint