# .github/actions/run-e2e-tests/action.yml
name: 'Run E2E Tests'
description: 'Creates .env file and runs end-to-end tests'
runs:
  using: "composite"
  steps:
    - name: Create .env file for tests
      shell: bash
      run: |
        echo "HTTP_PORT=3000" >> .env
        echo "HTTP_HOST=http://localhost:3000" >> .env
        echo "POSTGRES_HOST=localhost" >> .env
        echo "POSTGRES_PORT=5432" >> .env
        echo "POSTGRES_USER=testuser" >> .env
        echo "POSTGRES_PASSWORD=testpassword" >> .env
        echo "POSTGRES_DATABASE=testdb" >> .env
        echo "NODE_ENV=test" >> .env
    - name: Run e2e tests
      shell: bash
      run: yarn test:e2e