# .github/workflows/reusable-deploy.yml

name: Reusable Deploy

on:
  workflow_call:
    # Определяем входные параметры, которые будет принимать этот воркфлоу
    inputs:
      environment_name:
        required: true
        type: string
      environment_url:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      compose_file:
        required: true
        type: string
    # Определяем секреты, которые мы ожидаем получить от вызывающего воркфлоу
    secrets:
      remote_host:
        required: true
      remote_user:
        required: true
      remote_key:
        required: true
      remote_path:
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment_name }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment_name }}
      url: ${{ inputs.environment_url }}
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.remote_host }}
          username: ${{ secrets.remote_user }}
          key: ${{ secrets.remote_key }}
          script: |
            cd ${{ secrets.remote_path }}
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            export IMAGE_TAG=${{ inputs.image_tag }}
            docker pull ghcr.io/${{ github.repository }}:${IMAGE_TAG}
            docker-compose -f docker-compose.yml -f ${{ inputs.compose_file }} up -d --force-recreate